config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  root to: "submissions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def index
    @submissions = Submission.all
  end

  def new
    @submission = Submission.new
  end

  def show

  end

  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: "Submission was succesfully created"}
      else
        format.html { render :new}
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @submission.destroy
      respond_to do |format|
        format.html {redirect_to submissions_url, notice: "Submission was successfully destroyed"}
      end
  end


  private

  def submission_params
    params.require(:submission).permit(:title, :body)
  end

  def set_submission
    @submission = Submission.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissons_helper.rb
module SubmissonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing101</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= flash[:notice]%></p>
    <%= yield %>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= form.submit  %>
<% end %>

app/views/submissions/edit.html.erb
<%= render 'submissions/form', submission: @submission  %>

app/views/submissions/index.html.erb
<h1>Submissions</h1>
<%= link_to "New Submission", new_submission_path %>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

<% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.title %></td>
    <td><%= submission.body %></td>
    <td><%= link_to "Edit", edit_submission_path(submission.id) %></td>
    <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/submissions/new.html.erb
<%= render 'submissions/form', submission: @submission  %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p class="submission-title">
  <strong>Title:</strong> <%= @submission.title %>
</p>

<p class="submission-body">
  <strong>Body:</strong> <%= @submission.body %>
</p>

<%= link_to 'Edit Submission', edit_submission_path(@submission) %>